function tf = defaultIsTransient(err)
%DEFAULTISTRANSIENT True for retryable errors (network/5xx).
transientIds = [ ...
    "MATLAB:webservices:Timeout", ...
    "MATLAB:webservices:ConnectionRefused", ...
    "MATLAB:webservices:CopyContentToDataStreamError", ...
    "MATLAB:webservices:HTTP500StatusCodeError", ...
    "MATLAB:webservices:HTTP502StatusCodeError", ...
    "MATLAB:webservices:HTTP503StatusCodeError", ...
    "MATLAB:webservices:HTTP504StatusCodeError"];
tf = any(string(err.identifier) == transientIds);
end
